/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useEffect, useRef } from 'react'
import { useGLTF, useAnimations } from '@react-three/drei'
import { useMouseReactivePosition } from './ReactivePosition'

export default function Model(props) {
  const group = useMouseReactivePosition(0, 0, {
    ease: 0.1, scaleX: 0.25, scaleY: -0.15, throttleMs: 50
  })
  const { nodes, materials, animations } = useGLTF('./models/Tshirt.gltf')
  const { actions } = useAnimations(animations, group)

  useEffect(() => {
    const firstAnimation = Object.keys(actions)[0]
    actions[firstAnimation]?.play()
  
    return () => actions[firstAnimation]?.stop()
  }, [actions])

  return (
    <group ref={group} {...props} dispose={null}>
      <group name="Scene">
        <mesh
          name="cloth_parent"
          castShadow
          receiveShadow
          geometry={nodes.cloth_parent.geometry}
          material={materials['Shirt Texture']}
          position={[0, -6, 0]}
          scale={0.005}
        />
      </group>
    </group>
  )
}

useGLTF.preload('./models/Tshirt.gltf')